// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package forms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/admin"
	"github.com/mikestefanello/pagoda/pkg/routenames"
	"github.com/mikestefanello/pagoda/pkg/ui"
	"github.com/mikestefanello/pagoda/pkg/ui/components"
	"net/http"
	"net/url"
)

func AdminEntity(r *ui.Request, entityType admin.EntityType, values url.Values) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		isNew := values == nil
		getValue := func(name string) string {
			if value := r.Context.FormValue(name); value != "" {
				return value
			}
			if values != nil && len(values[name]) > 0 {
				return values[name][0]
			}
			return ""
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form method=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(http.MethodPost)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/ui/forms/admin_entity.templ`, Line: 26, Col: 31}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, f := range entityType.GetSchema() {
			if isNew || !f.Immutable {
				if f.Type == field.TypeString {
					inputType := "text"
					placeholder := ""
					help := ""
					if f.Sensitive {
						inputType = "password"
						if !isNew {
							placeholder = "*****"
							help = "SENSITIVE: This field will only be updated if a value is provided."
						}
					}
					templ_7745c5c3_Err = components.InputField(components.InputFieldParams{
						Name:        f.Name,
						InputType:   inputType,
						Label:       admin.FieldLabel(f.Name),
						Value:       getValue(f.Name),
						Placeholder: placeholder,
						Help:        help,
					}).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else if f.Type == field.TypeTime {
					templ_7745c5c3_Err = components.InputField(components.InputFieldParams{
						Name:      f.Name,
						InputType: "datetime-local",
						Label:     admin.FieldLabel(f.Name),
						Value:     getValue(f.Name),
					}).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else if f.Type == field.TypeInt || f.Type == field.TypeInt8 || f.Type == field.TypeInt16 || f.Type == field.TypeInt32 || f.Type == field.TypeInt64 || f.Type == field.TypeUint || f.Type == field.TypeUint8 || f.Type == field.TypeUint16 || f.Type == field.TypeUint32 || f.Type == field.TypeUint64 || f.Type == field.TypeFloat32 || f.Type == field.TypeFloat64 {
					templ_7745c5c3_Err = components.InputField(components.InputFieldParams{
						Name:      f.Name,
						InputType: "number",
						Label:     admin.FieldLabel(f.Name),
						Value:     getValue(f.Name),
					}).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else if f.Type == field.TypeBool {
					templ_7745c5c3_Err = components.Checkbox(components.CheckboxParams{
						Name:    f.Name,
						Label:   admin.FieldLabel(f.Name),
						Checked: getValue(f.Name) == "true",
					}).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else if f.Type == field.TypeEnum {
					options := make([]components.Choice, 0, len(f.Enums)+1)
					if f.Optional {
						options = append(options, components.Choice{
							Label: "-",
							Value: "",
						})
					}
					for _, enum := range f.Enums {
						options = append(options, components.Choice{
							Label: enum,
							Value: enum,
						})
					}
					templ_7745c5c3_Err = components.SelectList(components.OptionsParams{
						Name:    f.Name,
						Label:   admin.FieldLabel(f.Name),
						Value:   getValue(f.Name),
						Options: options,
					}).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var3 string
					templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(f.Name)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/ui/forms/admin_entity.templ`, Line: 93, Col: 16}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " not supported</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
		}
		templ_7745c5c3_Err = components.ControlGroup(
			components.FormButton(components.ColorPrimary, "Submit"),
			components.ButtonLink(
				components.ColorNone,
				r.Path(routenames.AdminEntityList(entityType.GetName())),
				"Cancel",
			),
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CSRF(r).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
